apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
    - name: app
      image: pseudorandomized/pod-debugger:latest
      securityContext:
        privileged: true
 # serviceAccountName: ...
 # automountServiceAccountToken: false